.circleci/config.yml
changes/pr18.yaml
docker/infrastructure/docker-compose.yml

Update Hasura to 1.3

---

src/prefect_server/api/states.py
tests/api/test_states.py

This PR fixes a bug in the Lazarus query that relied on a heartbeat being set for Submitted states.  I think this call was lost in the server migration.
So that Lazarus functions properly.

Fix Lazarus

---

.github/labeler.yml

Labeling "tests" will create too much noise

Remove tests/ from labeler

---

.github/labeler.yml

Creates an automatic label just for migrations

Add migration label

---

changes/pr40.yaml
src/prefect_server/api/flow_groups.py
src/prefect_server/api/runs.py
tests/api/test_flow_groups.py
tests/graphql/test_flow_groups.py

This PR dedupes Flow Group labels when set per @znicholasbrown 's request
Clarity

Flow group labels touchup

---

setup.py

Remove pytest-xdist

---

changes/pr45.yaml
src/prefect_server/cli/dev.py
src/prefect_server/cli/services.py

This PR removes the unused UI from the services command.
Tidying up.

Remove ui from services CLI command

---

.circleci/config.yml
changes/pr59.yaml
setup.py
src/prefect_server/graphql/query.py
src/prefect_server/graphql/schema/schema.graphql
tests/graphql/queries/test_api.py

Hardcoded to "normal", for UI / Cloud compatibility. 
**cc:** @znicholasbrown

Add API mode to queryable reference info

---

Dockerfile
changes/pr60.yml

* Reduce overall size of final docker image by using less layers.
* Added default UTF-8 locale to system.
* Avoid having pip cache by using --no-install-cache for Prefect Core library.
* Added comments to Dockerfile
* Shouldn't affect CI process since build arguments were left the same
* Changed base image from **python:3.7** to **python:3.7-slim**
* Overall image size of latest tag uncompressed was reduced from **1.01 GB** to **356 MB**, a _decrease_ of **64.7%**.
* Added default locale UTF-8
* Remove **git** after installing Prefect and Prefect Server.
* Added **PREFECT_SERVER_VERSION** build argument to Dockerfile. Defaults to **master**
* Added **PYTHON_VERSION** build argument to Dockerfile. Defaults to **3.7**
* Added image labels.
* Both **PREFECT_VERSION** and …

Dockerfile Refactoring and Improvements

---

changes/pr69.yaml
src/prefect_server/cli/dev.py

When running `prefect-server dev infrastructure`, automatically upgrade the database
Improves local dev experience
This PR:

Upgrade database automatically on startup

---

src/prefect_server/api/flows.py

Has no effect currently, but good to future proof any changes to our Flows API

Use registered API endpoint instead of namespaced function

---

.github/PULL_REQUEST_TEMPLATE.md
changes/issue96.yaml

This PR rebuilds the Server docker images to include https://github.com/PrefectHQ/prefect/pull/3394 (currently only in the master branch of Core), which will allow for Flows to be scheduled at the exact same time with distinct Parameter default values.
Also removes the "Changes" section of our PR template, which did not feel sufficiently distinct enough from our other sections.  Summary + Importance should be sufficient to describe a PR.
Closes #96 
This PR:

Parameter Scheduling Feature

---

changes/issue96.yaml
changes/pr100.yml
changes/pr103.yaml
changes/pr12.yml
changes/pr3.yml
changes/pr60.yml
changes/pr76.yml
changes/pr89.yml
update_changelog.py

There are a lot of files in there that need to be cleaned up and exist with `.yml` instead of `.yaml`

Update changelog generation script to look for .yml files

---

Changelog.md
changes/pr107.yaml
changes/pr109.yaml

Released on October 13, 2020.
- Allow for scheduling changing labels on a per-flow run basis - [#109](https://github.com/PrefectHQ/server/pull/109)
- Fixes issue with Agent Config schema - [#107](https://github.com/PrefectHQ/server/pull/107)

Update changelog for release

---

changes/pr144.yaml
src/prefect_server/api/runs.py
src/prefect_server/services/loop_service.py

Unused, intended for downstream use cases.
This PR:

Add shutdown flag for loop services

---

changes/pr146.yaml
src/prefect_server/database/hasura.py
src/prefect_server/database/orm.py
tests/database/test_hasura.py
tests/database/test_orm.py

Adds support for the following Hasura update types:
- append
- prepend
- delete key
- delete elem
This PR:

Add support for hasura update operations: append, prepend, delete key, delete elem

---

changes/pr149.yaml

Add changes/ entry for task run name index

---

changes/pr148.yaml
helm/prefect-server/templates/NOTES.txt
helm/prefect-server/templates/agent/deployment.yaml

Listen on all the interfaces for health checks 
Also, improve formatting
Prevent crash loops and unresponsive agent
This PR:

Listen on all agent interfaces for health checks 

---

changes/pr-159.yaml
helm/prefect-server/README.md

Add more details to helm documentation on how to tackle the issue when UI loads but the dashboard is blank.

Improve troubleshooting documentation

---

.circleci/config.yml
src/prefect_server/database/orm.py
tests/api/test_runs.py
tests/api/test_states.py
tests/graphql/test_states.py

Removes references to old objects (see https://github.com/PrefectHQ/prefect/pull/3838)
**cc:** @jcrist @joshmeek

Compatibility for 0.14

---

src/prefect_server/services/agents/local_agent.py

Minor interface change https://github.com/PrefectHQ/prefect/pull/3969 caused some of our service tests to fail

Fix tests in response to some Core changes

---

Changelog.md
changes/pr191.yaml

- Add `tini` init process to GraphQL and Apollo containers to reap zombies - [#191](https://github.com/PrefectHQ/server/pull/191)

Cut changelog for release

---

Changelog.md
changes/pr209.yaml

Cut changelog for 21.03.10

---

changes/pr224.yaml
src/prefect_server/services/towel/scheduler.py

Ensures that errors in the scheduler do not interrupt other scheduling operations
This PR:

Return exceptions to scheduler

---

changes/pr259.yaml
src/prefect_server/api/flows.py
src/prefect_server/services/loop_service.py
src/prefect_server/services/towel/lazarus.py
src/prefect_server/services/towel/zombie_killer.py

Adds traceback information to logs.
Helps debuggability in the face of unexpected errors
This PR:

Add tracebacks to logs

---

Changelog.md
changes/pr259.yaml
changes/pr261.yaml

Released on July 6, 2021.
- Add traceback info to some unexpected logs for debugging - [#259](https://github.com/PrefectHQ/server/pull/259)
- Add the option to defer setting a flow run state to scheduled when creating a FlowRun - [#261](https://github.com/PrefectHQ/server/pull/261)

Release July 06, 2021

---

src/prefect_server/api/flows.py

This PR:
- ~[ ] adds a change file in the `changes/` directory (if appropriate)~

Decrease batch size

---

.circleci/config.yml
src/prefect_server/api/flows.py
src/prefect_server/config.toml

This PR makes task/edge batch size a configuration option.
This PR:
- ~[ ] adds a change file in the `changes/` directory (if appropriate)~

Make insert batch size configurable

---

helm/prefect-server/README.md
helm/prefect-server/values.yaml

This PR:
- [-] adds new tests (if appropriate)
- [-] adds a change file in the `changes/` directory (if appropriate)

Clarify docs for Server helm chart

---

src/prefect_server/api/flows.py

Backend version of https://github.com/PrefectHQ/prefect/pull/5106

Fix mysterious issue with bad serialized edge data

---

Changelog.md
changes/pr306.yaml

- Preserves structural representation of serialized flows - [#306](https://github.com/PrefectHQ/server/pull/306)
- Upgrade `apollo-server` to address GraphQL playground vulnerability. See [the advisory](https://github.com/apollographql/apollo-server/security/advisories/GHSA-qm7x-rc44-rrqw) for details.

Release November 09, 2021

---

changes/pr314.yaml
helm/prefect-server/templates/serviceaccount.yaml
helm/prefect-server/values.yaml

Allows for setting custom annotations on the Service Role
Enables usage of features such as EKS RBAC 
This PR:

Add service role annotations

---

setup.py

See 
- https://github.com/PrefectHQ/prefect/pull/5179
- https://github.com/PrefectHQ/prefect/pull/5157

Update requirements to match changes in core

---

Changelog.md
services/apollo/src/index.js

Allowing users to disable/enable apollo playground if needed.

Added the ability to disable Apollo Playground

---

services/apollo/src/index.js

Fixed a small bug introduced by my last PR

Fixed type confusing bug

---

Changelog.md
changes/pr337.yml

- Upgrade version of Hasura GraphQL engine to v2.1.1 - [#337](https://github.com/PrefectHQ/server/pull/337)

Release 2022.01.25

---

helm/prefect-server/README.md

Just a question / assumption: the version used for Helm installation should be updated.  Right?
To help new Prefect users onboard.
This PR:

Update chart version used in README.md

---

Changelog.md
helm/prefect-server/README.md

Releasing #362 for a new latest Helm chart version

Release 2022.04.14

---

src/prefect_server/services/towel/zombie_killer.py
tests/services/test_zombie_killer.py

This PR closes:
- https://github.com/PrefectHQ/prefect/issues/5717

Chore: Change Zombie Killer log message

---

.circleci/config.yml
setup.py

Extends #381. This branch was renamed during the 2.0 release

Update CI prefect branch reference from `master` to `1.x`

---

.circleci/config.yml
setup.py

This prevents 2.x from being installed.
Includes #383 and #382 to fix CI.

Add upper pin to Prefect core version

---

.circleci/config.yml

Targetting missing file failure in https://app.circleci.com/pipelines/github/PrefectHQ/server/1451/workflows/05072e83-4f4b-48c3-a1aa-6ca8b9237e87/jobs/7420

Set `attach-at` to the apollo directory

---

src/prefect_server/api/cloud_hooks.py

Backport: Run black to format code

---

.circleci/config.yml

Backport: Install from 0.15.x tag instead of 1.x

---

README.md

Add a note indicating that Prefect 2 is available, and add links.
This PR:

chore: add note about Prefect 2

---

README.md
helm/prefect-server/README.md

Add notes for Prefect 2 Server chart

---

.github/CODEOWNERS

Remove CODEOWNERS so that anyone at Prefect can review and merge changes to this repository
This PR:

Remove CODEOWNERS from server repo
