PrefectHQ/server

- changes/pr37.yaml
- src/prefect_server/api/flows.py
- tests/api/test_flows.py
This PR sets a Flow's schedule to inactive if neither it nor its Flow Group have a schedule.  Not a bug, but the UI would display an active schedule with a warning message anytime I registered a Flow with no schedule and that was bothering me.
Better match expectations.  **cc:** @zhen0
> Toggle set schedule active intelligently

- changes/EXAMPLE.yaml
- changes/pr35.yaml
- services/hasura/migrations/versions/metadata-3398e4807bfb.yaml
- services/hasura/migrations/versions/metadata-b9086bd4b962.yaml
- services/postgres/alembic/env.py
- services/postgres/alembic/versions/2020-08-08T205817_remove_state_id_foreign_keys.py
- src/prefect_server/api/runs.py
- src/prefect_server/database/_models.py
- tests/api/test_cloud_hooks.py
- tests/api/test_runs.py
- tests/database/test_migrations.py
- tests/database/test_state_triggers.py
- update_changelog.py
This PR removes a foreign key on `task_run.state_id` and `flow_run.state_id` that once pointed to the current state; it is unused and creates performance issues.
> Remove unused state_id foreign key

- .circleci/config.yml
Server will begin versioning its "releases" (which are essentially just docker tags) with Calendar Versioning (YYYY-MM-DD(.*)).  This PR prepares our circle jobs to monitor for tags of this form.
> Update circle jobs to build and tag on cal-ver versioning schemes

- changes/issue86.yaml
- src/prefect_server/api/flows.py
- tests/api/test_flows.py
This PR consolidates all logic for setting a flow schedule to active in the 🥁 `set_schedule_active` mutation.  This will make it much simpler to maintain and test moving forward.
The following behavioral changes will occur as a consequence of this PR:
- closes #86 (error returned but schedule was still set to active)
- allows for default parameters to come from clocks, flow group defaults, or both! (this is new functionality)
- allows for flows with required parameters and schedules to still be registered, but they will not have their schedule set to active (this is drastically different behavior from the current situation where an error is raised prior to creation)
Fixes a few outstanding bugs + cleans up what I think was tech debt
This PR:
> Fix setting schedules to active

- changes/pr89.yml
- src/prefect_server/api/agents.py
- src/prefect_server/api/cloud_hooks.py
- src/prefect_server/api/flow_groups.py
- src/prefect_server/api/flows.py
- src/prefect_server/api/logs.py
- src/prefect_server/api/messages.py
- src/prefect_server/api/projects.py
- src/prefect_server/api/runs.py
- src/prefect_server/api/states.py
- src/prefect_server/api/tenants.py
Attempting to access the models via
```python
from prefect import api
api.models.Agent
```
Raises a `box.BoxKeyError: "'Box' object has no attribute 'models'"` and instead it needs to be `from prefect import models`.
Updates all API files that called `prefect_server.database.models` in favor of `prefect.models`
Code reuse and ensuring smooth repo-specific functionality
This PR:
> Use prefect.models in favor of database.models

- src/prefect_server/api/flows.py
- tests/api/test_flows.py
This error is raised in Cloud as well, and might be misleading when encountered there.
> Update wording in error message

- changes/pr103.yaml
- services/hasura/migrations/versions/metadata-24f10aeee83e.yaml
- services/postgres/alembic/versions/2020-09-30T123806_add_label_column_to_flow_runs.py
- src/prefect_server/api/cloud_hooks.py
- src/prefect_server/api/runs.py
- src/prefect_server/api/states.py
- src/prefect_server/cli/dev.py
- src/prefect_server/database/models.py
- src/prefect_server/database/orm.py
- src/prefect_server/graphql/agents.py
- src/prefect_server/graphql/runs.py
- src/prefect_server/graphql/schema/runs.graphql
- src/prefect_server/services/towel/lazarus.py
- src/prefect_server/services/towel/zombie_killer.py
- tests/api/test_runs.py
- tests/database/test_orm.py
- tests/fixtures/database_fixtures.py
- tests/graphql/test_runs.py
This PR refactors `labels` to be specified at the flow run level (as opposed to the flow / flow group level).  Moreover, the migration will set the labels on all currently `Scheduled` runs to the correct values so that no work is missed and no backwards compatibility issues arise within the application code.
- consolidates all our label logic into one place: `create_flow_run`
- will allow the UI to query for `flow_run{labels}` instead of recreating the flow / flow group logic as it currently does
- will allow users to configure labels on a _per run_ basis
- will allow users to schedule a flow to run multiple times simultaneously with different label sets
This PR:
> Run Labels refactor

- changes/pr111.yaml
- src/prefect_server/api/flows.py
- tests/api/test_flows.py
This PR updates the scheduler to allow for scheduling runs of the same flow at the exact same time, so long as the runs will have either different default parameter values or different run labels.  The solution relies on a somewhat messy idempotency key generation that should be stable across schedulers.
Unlocks the last piece of the puzzle for parameter + label scheduling.
This PR:
> Allow for scheduling different parameters and run labels at the same time

- changes/pr117.yaml
- src/prefect_server/cli/dev.py
An error during database upgrade is hidden with a message "Database is not ready..."
- Only displays that the database is not ready when the exception is a refused connection
- Other exceptions are displayed and reraised
Example output
```
prefect-3.7 ❯ prefect-server dev infrastructure
Pulling postgres ... done
Pulling hasura   ... done
Database upgrade encountered fatal error:
(psycopg2.OperationalError) FATAL:  role "prefect" does not exist
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Exception caught; killing services (press ctrl-C to force)
... full traceback
```
Silencing exceptions during database setup makes it challenging to troubleshoot
This PR:
> Expose database upgrade errors during infra start

- setup.py
Starting the server is raising the following dependency error. Pinning urllib3 until this conflict is fixed with requests
```
graphql_1   | Traceback (most recent call last):
graphql_1   |   File "/usr/local/bin/prefect-server", line 15, in <module>
graphql_1   |     from pkg_resources import load_entry_point
graphql_1   |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in <module>
graphql_1   |     @_call_aside
graphql_1   |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
graphql_1   |     f(*args, **kwargs)
graphql_1   |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
graphql_1   |     working_set = WorkingSet._build_master() …
```
> Bound urllib3 to prevent dependency conflicts

- .circleci/config.yml
`PREFECT_SERVER_VERSION` is referenced within the API and Dockerfile but never differs from `master` as written, to fix:
- Sets `PREFECT_SERVER_VERSION` to the git tag for tagged CI image builds
The server version should be set correctly for tagged images
This PR:
> Set PREFECT_SERVER_VERSION during versioned docker builds

- changes/pr132.yaml
- helm/prefect-server/Chart.yaml
- helm/prefect-server/templates/_helpers.tpl
With the merge of #123 the repo contains helm chart for deploying in Kubernetes. However, for deploying with an existing postgres instance, there were some errors.
Completes #123 
This PR:
> Fix helm chart when using existing postgres instance

- .github/CODEOWNERS
Makes @madkinsz a CODEOWNER so he's auto-requested for reviews and his approval carries weight 🚀
> Make Michael a codeowner

- changes/pr134.yaml
- src/prefect_server/api/flows.py
- src/prefect_server/api/runs.py
- tests/api/test_flows.py
Through https://github.com/PrefectHQ/prefect/issues/3629 we observed that there is potential for duplicate runs to be scheduled due to expired idempotency keys (24 hours). To patch this behavior this PR moves the last scheduled run check to the step prior to creating an idempotency key based on the parameter defaults and labels.
Duplicate runs are a hugely unexpected behavior and this patch is necessary.
This PR:
> Fix scheduling duplicate runs with expired idempotency keys

- changes/pr139.yaml
- helm/prefect-server/templates/graphql/deployment.yaml
- helm/prefect-server/values.yaml
Fixes database migration failures for Azure managed Postgres due to connection string issues.
Azure Postgres instances have usernames "user@instance-name" which requires escaping as "user%40instance-name" for Hasura (and other database connections) to work correctly. However, for migrations, an `@` is required in place of the `%40`
This PR:
> Fix handling for managed postgres usernames with `@` signs

- src/prefect_server/cli/database.py
Removes the unused `database_url` option which does not have any effect because the database connstr is loaded in `services/postgres/alembic/env.py`
Misleading to have it but not have it work. Dangerous for migrations.
This PR:
> Remove `database_url` from 'server database upgrade'

- services/postgres/alembic/versions/2020-12-02T130956_add_index_for_task_run_names.py
Corresponding to https://github.com/PrefectHQ/cloud/pull/2884 adds a GIN trigram text search index on task run names
Necessary for reasonable global search of task run names
This PR:
> Add index on task run names for global search

- changes/pr-154.yaml
- helm/prefect-server/templates/agent/rbac.yaml
Enables agent role to get jobs/status.
Otherwise Prefect task RunNamespacedJob fail because it try to get the status of a job.
This PR:
> Add jobs/status to role for agent

- .circleci/config.yml
- changes/pr158.yaml
- setup.py
- src/prefect_server/services/towel/zombie_killer.py
- tests/services/test_zombie_killer.py
This PR updates the zombie killer to rely on _flow_ run heartbeats instead of individual task run heartbeats; we've found that task run heartbeat processes can be brittle and cause resource contention issues when working with thousands of parallel runs.  In addition, if the Flow Run process dies then the task runs it submits also die, so this change should not affect behavior.
Performance improvement!
This PR:
> Task run heartbeats refactor

- changes/pr161.yaml
- src/prefect_server/database/hasura.py
- src/prefect_server/database/orm.py
- tests/database/test_orm.py
Hasura supports custom root fields, which is now enabled in the ORM.
```python
class MyHasuraModel(HasuraModel):
__hasura_type__ = "flow"
__root_fields__ = {
'insert': 'custom_insert_flow_root_type',
'delete': 'delete_some_flows'
}
...
```
This PR:
> Add support for custom Hasura root fields

- src/prefect_server/database/hasura.py
- src/prefect_server/database/orm.py
- tests/api/test_flows.py
- tests/api/test_projects.py
- tests/api/test_runs.py
- tests/api/test_tenants.py
- tests/database/test_orm.py
- tests/graphql/test_flows.py
- tests/graphql/test_projects.py
- tests/graphql/test_runs.py
Closes #160 
Removes `.get()` and `.exists()` from the Hasura client (both brittle fields that depended on `by_pk` queries and were almost unused), as well as `.exists()` from the ORM, as it is easily replaced with `.where(id=id).first()`.
Removing brittle methods and dependencies on Hasura implementation details (like `by_pk`)
This PR:
> Remove .get() and .exists() methods on hasura client

- changes/pr157.yaml
- helm/prefect-server/templates/agent/rbac.yaml
The next release of core will allow agents to report events for pending pods that belong to jobs it creates. (PrefectHQ/prefect#3783) In order to use this functionality the in-cluster agent in the helm chart should have the proper resources in the RBAC.
> Add events resource to Kubernetes Agent RBAC helm chart template

- changes/pr153.yaml
- services/apollo/Dockerfile
Upgrades outdated Apollo Node to 14.15.1 LTS
- Requires installation of curl in Dockerfile
- Security and performance fixes
- Beginning https://github.com/PrefectHQ/cloud/issues/2714
- Checkout branch
- Build with `cd services/apollo && docker built -t apollo .`
- Checkout core branch `patch-apollo-upgrade-test`
- Run prefect server with `prefect server start --skip-pull`
This PR:
> Upgrade Apollo NodeJS to `14.15.1`

- changes/pr165.yaml
- helm/prefect-server/templates/agent/deployment.yaml
- helm/prefect-server/templates/apollo/deployment.yaml
- helm/prefect-server/templates/graphql/deployment.yaml
- helm/prefect-server/templates/hasura/deployment.yaml
- helm/prefect-server/templates/towel/deployment.yaml
- helm/prefect-server/templates/ui/deployment.yaml
- helm/prefect-server/values.yaml
Adds the possibility to the helm chart to configure the strategy of deployment.
Allows to configure rolling updates, for instance maybe someone (me) wants to tune the surge and unavailable parameters. Example of `values.yaml`
```
apollo:
replicas: 3
strategy:
type: RollingUpdate
rollingUpdate:
maxSurge: 0
maxUnavailable: 1
affinity: 
podAntiAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchExpressions:
- key: app.kubernetes.io/component
operator: In
values:
- apollo
topologyKey: kubernetes.io/hostname
```
This PR:
> Helm: configure strategy for deployment

- .github/workflows/labeler.yml
Should allow running labeler on PRs from forks.
> Use `pull_request_target` in labeler

- Changelog.md
- changes/pr157.yaml
- changes/pr169.yaml
- src/prefect_server/api/flow_groups.py
- src/prefect_server/graphql/flow_groups.py
- src/prefect_server/graphql/schema/flows.graphql
- tests/api/test_flow_groups.py
- tests/graphql/test_flow_groups.py
This PR exposes a new `timezone` input to the `set_flow_group_schedule` GraphQL mutation.  Allowable timezones can be obtained via `pendulum.timezones` in Python (**cc:** @znicholasbrown / @ThatGalNatalie in case you need to audit this list and ensure the UI can serve these values appropriately).
For learning purposes, this PR demonstrates how the lifecycle of an API request works: clients send JSON payloads corresponding to GraphQL inputs.  The GraphQL resolver layer then manipulates / handles those, and passes them deeper into the API function layer.  Here, additional manipulation / validation may occur before placing the payloads into the database.  It is usually much easier for testing purposes to contain most of the logic / validation in the API layer.
In this case, the user-facing …
> Flow Group schedule timezones

- services/apollo/post-start.sh
Running `prefect server start` with `--graphql-port ####` fails because it sets `GRAPHQL_SERVICE_PORT` and the apollo service queries `$GRAPHQL_SERVICE_HOST:$GRAPHQL_SERVICE_PORT/health` which is in the docker network and should be the default port still. 
- Replaces this query with the health url that is available as an environment variable `PREFECT_API_HEALTH_URL`
- Adds a printout that it's doing a health check so it doesn't just silently hang
Also resolved by https://github.com/PrefectHQ/prefect/pull/3933 -- it looks like `core` was misusing the environment variable. That said, it seems weird that we are building the health url when it already is in the env so this PR may stand.
- Allows users to properly specify custom graphql ports
- Helps debug failing apollo startups
This PR:
> Use and display health url during apollo service startup

- changes/pr174.yaml
- src/prefect_server/database/orm.py
- tests/database/test_orm.py
- Fixes tests that were broken (they called a non-existent mock route, but because it was a mock... it didn't error)
- Adds a `sum` aggregate to the ORM:
```
await models.Flow.where().sum(['version'])
```
- Adds ORM tests for aggregates
This PR:
> Fix ORM tests and add `sum` aggregate 

- changes/pr177.yaml
- services/hasura/migrations/versions/metadata-9116e81c6dc2.yaml
- services/postgres/alembic/versions/2021-01-20T132230_add_description_to_flow_group_table.py
- src/prefect_server/api/flow_groups.py
- src/prefect_server/database/models.py
- src/prefect_server/graphql/flow_groups.py
- src/prefect_server/graphql/schema/flows.graphql
- tests/api/test_flow_groups.py
- tests/graphql/test_flow_groups.py
This PR adds formal support for Flow Group descriptions that can be edited via API.  In particular, we now have the following ways of creating and managing descriptions for flows and flow groups:
- passing a `description` when calling `mutation{create_flow}` (this has been supported for a long time -- *cc* @jcrist in case you wanted to begin using this in Core)
- calling the `set_flow_group_description` mutation (this is what this PR adds)
Note that this flow group field will be treated _slightly_ differently from other flow group fields in that the description will not be an override.  Instead, it will be editable and persistent, but individual versions may still have their own descriptions displayed (but note that they won't be editable).
All descriptions will support markdown …
> First class descriptions

- .circleci/config.yml
- changes/pr178.yaml
We began seeing some build errors recently (interestingly enough, they appeared to be non-deterministic) because Prefect Server's versioning scheme was not [PEP 440](https://www.python.org/dev/peps/pep-0440) compliant, resulting in invalid wheels.
This PR updates our jobs to detect versions based on `YYYY.MM.DD` instead of `YYYY-MM-DD`
> Update tag versioning scheme to be PEP 440 compliant

- changes/pr185.yaml
- src/prefect_server/api/flows.py
- src/prefect_server/api/states.py
- tests/api/test_flows.py
Currently, whenever a flow is archived we _delete_ all outstanding runs for that flow that are still in a `Scheduled` state (because they can't run).  This works well for auto scheduled runs; however, users who create ad-hoc runs for a flow that maybe take a while to begin (due to concurrency limits, or maybe an agent malfunction) might register a new version in the meantime.  In this situation, the deletion of these runs can be very mysterious and unexpected.  @znicholasbrown noted that we could instead _cancel_ these runs so that there is a record of what happened.
More transparent UX.
This PR:
> Better archiving experience

- changes/pr189.yaml
- src/prefect_server/utilities/graphql.py
- tests/database/test_hasura.py
This PR captures all errors from GraphQL -> Hasura that have "connect" in the exception and converts them into a uniform "database query error".  Other clients handle these errors specially, so we can rely on client-side behavior here instead of rolling custom retries in this code path.  In looking at this it does seem we have some tech debt in error handling around here that we might want to revisit - low priority though.
**cc:** @mashun4ek 
Helps with some fault tolerance in rare cases by relying on other clients' handling of "database query error"s.
This PR:
> Uniformize errors

- Dockerfile
- changes/pr191.yaml
- services/apollo/Dockerfile
Finishes #190.
--------
Installs `tini` and uses as an entrypoint to graphql/apollo containers to reap zombie processes.
- Uses sha256 instead of gpg  for checksum verification (both are recommended checks but sha256 is significantly lighter with a 2x faster image build time)
- Fails to run when build on an M1 machine with
```
❯ docker run -it 932c6511928bbb40c364b9a414333e802c9fe8a9edd76dfb7d58cbf59df2c613
/lib64/ld-linux-x86-64.so.2: No such file or directory
```
I've added an `ARCH` flag so you can `docker build . --build-arg ARCH=arm64` for development builds. I presume that once we use apt it'll just grab the correct binary automatically.
Fixes PrefectHQ/prefect#4114
This PR:
> Add tini to graphql and apollo containers

- .circleci/config.yml
- changes/pr188.yaml
- docker/infrastructure/docker-compose.yml
- helm/prefect-server/README.md
- helm/prefect-server/templates/hasura/deployment.yaml
- helm/prefect-server/values.yaml
Upgrade hasura to 1.3.3.
Important to be up to date :)
This PR:
- [-] adds new tests (if appropriate)
> Upgrade hasura

- Dockerfile
- changes/pr198.yaml
- services/apollo/Dockerfile
- Upgrades the `apollo` image to use `buster` instead of `stretch` Debian. 
- Changes the `server` image to explicitly use `buster` but should not change anything as it was implicit before
- Consistent base OS
- Security patches (see #198) 
This PR:
> Explicitly use debian buster for apollo/server images

- changes/pr199.yaml
- services/apollo/Dockerfile
Now that we're using a more recent debian version, we can install `tini`
from apt instead of github.
> Install tini from apt in apollo image

- changes/pr202.yaml
- src/prefect_server/api/flow_groups.py
- src/prefect_server/api/flows.py
- src/prefect_server/api/runs.py
- Adds a transactional delete to `delete_flow_run` that first deletes `task_run_states` and `task_runs` outer -> innner rather than the default inner -> outer relationships
- Uses the `delete_flow_run` API to delete auto-scheduled flow runs
Closes #200 
This PR:
> Improve `delete_flow_run` performance by avoiding slow deletion triggers

- Changelog.md
- changes/pr188.yaml
- changes/pr198.yaml
- changes/pr199.yaml
- changes/pr201.yaml
- changes/pr202.yaml
Released on March 4, 2021.
- Upgrade hasura version to 1.3.3 - [#188](https://github.com/PrefectHQ/server/pull/188)
- Upgrade apollo base image to debian-buster - [#198](https://github.com/PrefectHQ/server/pull/198)
- Install `tini` from apt instead of GitHub in apollo image - [#199](https://github.com/PrefectHQ/server/pull/199)
- Fixed the execution of the `create-tenant-job` in the Helm charts to allow for custom Apollo ports - [#201](https://github.com/PrefectHQ/server/pull/201)
- Improve `delete_flow_run` performance by avoiding slow deletion triggers - [#202](https://github.com/PrefectHQ/server/pull/202)
- Server instances with managed databases require [manual SQL to upgrade](https://github.com/PrefectHQ/server/tree/master/helm/prefect-server#Upgrading-Hasura) - …
> Release March 4, 2021

- changes/pr206.yaml
- src/prefect_server/api/flows.py
Improves performance of auto-scheduled flow run deletion during `api.flows.archive_flow` by using the `delete_flow_run` API (#202)
This PR:
> Use `delete_flow_run` API to delete scheduled runs on archive

- changes/pr204.yaml
- src/prefect_server/utilities/exceptions.py
- src/prefect_server/utilities/graphql.py
- tests/database/test_hasura.py
- tests/utilities/test_exceptions.py
- tests/utilities/test_graphql.py
To improve error handling in Server and Cloud, we replace the obscure `ValueError("database query error")` with a simple `APIError` with a fixed message. This also consolidates the `ServerException` base into a `PrefectBackendException` in preparation for shared custom exceptions across Server/Cloud.
Supersedes https://github.com/PrefectHQ/cloud/pull/3103 and will require a follow-up in Cloud (https://github.com/PrefectHQ/cloud/pull/3144) to use these exceptions instead of doubly defined `CloudException` types.
Improves exception handling traces at a low level.
This PR:
> Add `APIError` to replace "database query error"

- changes/pr207.yaml
- src/prefect_server/api/agents.py
Matching GQL API, field is not nullable in the DB
> Allow agents to be created with empty settings

- .github/workflows/helm-release.yml
- helm/prefect-server/README.md
- helm/prefect-server/templates/agent/deployment.yaml
- helm/prefect-server/templates/ui/deployment.yaml
- helm/prefect-server/values.yaml
Of course, in #209 I was testing a tag that _also_ existed in the UI but the UI is not guaranteed to be released at the same time as Server. Therefore the UI needs to rely on a different tag.
Now, we'll pull the latest core and UI tags and set them in `values.yaml` for the agent/ui.
The existing helm chart is broken :( will need to be re-released.
This PR:
- ~[ ] adds a change file in the `changes/` directory (if appropriate)~
> Fix Helm UI and Core version tags

- changes/pr217.yml
- src/prefect_server/config.toml
- src/prefect_server/services/graphql/server.py
Set graphql uvicorn server log level based on Prefect config.
Solves https://github.com/PrefectHQ/server/issues/216
Allows the user to control the access logs of the Prefect GraphQL service (which can become quite large on the default `DEBUG` level).
This PR:
> Set uvicorn server log level

- changes/pr215.yaml
- src/prefect_server/services/towel/scheduler.py
The scheduler currently orders flows by maximum scheduled start time, such that a flow (A) with its last scheduled run starting in one hour is prioritized over a flow (B) with its last scheduled run starting in one day.
However, this order could lead to flows being skipped across multiple batches. Consider if `A` is scheduled in the first batch of 500 flows, and `B` is the 501st flow. The scheduler schedules `A` such that it's maximum scheduled start time becomes later. This makes `B` the 500th flow, not the 501st. Therefore, when the scheduler queries for the second batch, it doesn't pick up `B`.
This circumstance is highly unusual due to the practical manner in which scheduling works (flows don't typically get to a point where they have a very low maximum scheduled start time and then …
> Update scheduler to have deterministic order

- changes/pr218.yaml
- services/hasura/migrations/versions/metadata-459a61bedc9e.yaml
- services/postgres/alembic/versions/2021-03-16T221106_improve_run_triggers_to_handle_same_.py
- tests/database/test_state_triggers.py
This PR modifies the trigger that updates run objects to ensure that it fires when the run has a null version or a version equal to the state being inserted. This can very rarely happen when the run was inserted with a manually-supplied version immediately prior to the state being inserted with the same version. It doesn't happen in application code but users could trip over it without this protection.
This PR:
> Fix situation where trigger doesn't fire if state version matches run

- changes/pr221.yaml
- helm/prefect-server/templates/agent/rbac.yaml
Add permissions to agent role (pods/log, services, poddisruptionbudgets). Closes #220 
Dask KubeCluster [rbac list](https://kubernetes.dask.org/en/latest/kubecluster.html#role-based-access-control-rbac).
Resolve permission errors when using DaskExecutor.  
This PR:
- [-] adds new tests (if appropriate)
> Helm update rbac agent

- tests/api/test_flows.py
- tests/fixtures/database_fixtures.py
- tests/services/test_scheduler.py
Tests go brrr
Scheduling 10 flows every single time a test runs is wasteful and adds up, even at a fraction of a second per test. This PR should cut test times by ~50%.
This PR:
> Disable flow scheduling for unit tests

- helm/prefect-server/templates/NOTES.txt
Fixes grammatical mistake in the notes printed after `helm install prefecthq/prefect-server`.
I noticed this in the logs during @lauralorenz 's demo (https://www.youtube.com/watch?v=EwsMecjSYEU) 😀 
Very minor grammatical fix. Just fixes a small grammatical error that might be distracting and might affect searches on this code.
This PR:
Thanks for your time and consideration.
> fix typo in helm notes

- changes/pr228.yaml
- src/prefect_server/api/flow_groups.py
- src/prefect_server/graphql/flow_groups.py
- src/prefect_server/graphql/schema/flows.graphql
- tests/api/test_flow_groups.py
- tests/graphql/test_flow_groups.py
Adds a new mutation for deleting flow groups.
An expected piece of the schema that will also allow the UI to more elegantly clean up flow groups.
This PR:
> Delete flow group mutation

- src/prefect_server/api/flows.py
- src/prefect_server/api/runs.py
- tests/api/test_flows.py
Scheduling runs concurrently instead of serially speeds up scheduling by ~25%
This PR:
> Schedule flow runs concurrently

- changes/pull229.yaml
- helm/prefect-server/README.md
- helm/prefect-server/templates/NOTES.txt
- helm/prefect-server/templates/apollo/ingress.yaml
- helm/prefect-server/templates/ui/ingress.yaml
- helm/prefect-server/values.yaml
Add ingress support for `ui` and `apollo` components in helm chart.
Many teams use ingress to expose services outside of kubernetes.
This PR:
> Helm ingress support

- changes/pr236.yaml
- src/prefect_server/api/flows.py
A try/except/pass does not have a log associated with it in the backend
This PR:
> Log `set_schedule_active` failure while creating a flow

- changes/pr247.yaml
- src/prefect_server/api/logs.py
- src/prefect_server/services/towel/lazarus.py
- src/prefect_server/services/towel/zombie_killer.py
This PR is a no-op from the perspective of Server - it allows for arbitrary `**kwargs` to be passed to `create_logs` so that services that call this function can declare that they want the logs written immediately.
For better compatibility between Server and Cloud in the backend.  **cc:** @mashun4ek 
This PR:
> Expose kwargs in create_logs and write immediately from services

- src/prefect_server/api/flows.py
Decrease batch size for task / edge insertion.
Flows with large numbers of edges and tasks can timeout.
This PR:
- ~[] adds new tests (if appropriate)~
- ~[ ] adds a change file in the `changes/` directory (if appropriate)~
> Decrease task/edge batch insertion size

- Changelog.md
- changes/pr247.yaml
Released on May 25, 2021.
- Introduce **kwargs to `create_logs` for Cloud compatibility - [#247](https://github.com/PrefectHQ/server/pull/247)
> Release May 25, 2021

- changes/pr261.yaml
- src/prefect_server/api/runs.py
- tests/api/test_runs.py
- tests/service_tests/test_diamond.py
- tests/service_tests/test_pause.py
- tests/service_tests/test_simple_map.py
- tests/service_tests/test_simple_reduce.py
This PR adds the option to defer setting a flow run to a Scheduled state upon creation.
Allows us to fix a race condition.
This PR:
> Add param to defer setting flow run state

- changes/pr273.yaml
- services/apollo/src/index.js
- src/prefect_server/config.toml
Increases the size limit for payloads in Apollo.  Goal is to allow for larger logs and an overall better UX for large payloads (5mb is still very reasonable).  
Better UX and auditing the logic between client / server side to ensure they match.  Will be following up with a Core PR to adjust the log limits accordingly.
This PR:
> Increase size limit

- changes/issue280.yaml
- src/prefect_server/api/flows.py
- src/prefect_server/config.toml
- src/prefect_server/services/towel/scheduler.py
- tests/services/test_scheduler.py
Fixes #280 
Add a configuration parameter to the scheduler that allows to change the hardcoded maximum number of upcoming runs that will be scheduled ahead per flow.
Changing this setting is needed when a single flow has more than 10 runs scheduled at exactly the same time (e.g. same cronstring). Currently, the scheduler will schedule 10 of them, the other ones will never be scheduled and fail silently.
The next scheduler update, these flow runs will be considered in the past and will not be scheduled anymore. Adding the configuration option will enable users to resolve the issue -- even if it is still a tricky one to detect.
This PR:
> Add max runs per flow parameter

- helm/prefect-server/templates/agent/rbac.yaml
Warning when applying the helm charts 
rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 RoleBinding
It would break the helm chart for anybody who is using v1.22+
Kubernetes 1.17 support has been dropped with the release of v1.22
This PR:
> change RoleBinding API to rbac.authorization.k8s.io/v1

- Changelog.md
- changes/issue280.yaml
- changes/pr273.yaml
- changes/pr277.yaml
- Make maximum number of scheduled runs per flow configurable - [#280](https://github.com/PrefectHQ/server/issues/280)
- Increase Apollo payload size limit to 5mb - [#273](https://github.com/PrefectHQ/server/pull/273)
- Separate out task and edge registration to better handle large flow registrations - [#277](https://github.com/PrefectHQ/server/pull/277)
- [Bouke Krom](https://github.com/bouke-sf)
> Release Sep 2, 2021

- changes/pr291.yaml
- src/prefect_server/api/states.py
- src/prefect_server/utilities/collections.py
- tests/api/test_states.py
- tests/graphql/test_states.py
- tests/utilities/test_collections.py
Adds an in memory in process submitted state lock. Closes #203
Currently it is possible for multiple agents to pick up the same scheduled flow_run, this enables a buffer so that if multiple agents try to run the same flow_run only one will succeed. 
This PR:
> submitted state lock

- changes/pr290.yaml
- changes/pr293.yaml
- services/apollo/src/index.js
Adding support for setting keep alive timeout of apollo service
Default keep alive setting causes issue with AWS ELB.  See linked blog post for details.
[Dealing with Intermittent 502's between an AWS ALB and Express Web Server](https://adamcrowder.net/posts/node-express-api-and-aws-alb-502/)
This PR:
> add handling a keepalive value to apollo

- changes/pr289.yaml
- helm/prefect-server/templates/agent/deployment.yaml
- helm/prefect-server/templates/apollo/deployment.yaml
- helm/prefect-server/templates/graphql/deployment.yaml
- helm/prefect-server/templates/hasura/deployment.yaml
- helm/prefect-server/templates/jobs/create_tenant.yaml
- helm/prefect-server/templates/towel/deployment.yaml
- helm/prefect-server/templates/ui/deployment.yaml
- helm/prefect-server/values.yaml
In aim to connect to private container registries, you can provide k8s secrets to `imagePullSecrets` on Prefect agent deployment. You can set env var `IMAGE_PULL_SECRETS` on `prefect-agent` deployment, or if using helm chart, you can set 
```
agent:
job:
imagePullSecrets:
- secret_name1
- secret_name2
```
Instead of modifying the logic [here](https://github.com/PrefectHQ/prefect/blob/2cd13929c7701e21b8b865c36291bdee39209b95/src/prefect/agent/kubernetes/agent.py#L115), let's use Go template function `join` to convert list to a string.
Closes #286 
@TylerWanner can you please take a look?
This PR:
- [-] adds new tests (if appropriate)
> Fix image pull secrets in Prefect Server helm chart

- changes/pr312.yaml
- helm/prefect-server/templates/agent/deployment.yaml
- helm/prefect-server/values.yaml
The current format of the Helm templating uses indentation one step too deep, resulting in formatting errors when used. This change corrects that indentation, and changes the default value in the `values.yaml` file to avoid incorrect warning messages.
Allows for actually providing custom environment variables to the agent
`values.yaml` file contents:
```
agent:
enabled: true
env:
- name: foo
value: bar
```
`helm template helm/prefect-server --values values.yaml` excerpt:
```
...
- name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
value: http://0.0.0.0:8080
- name: foo
value: bar
...
```
Accompanying error message:
`Error: YAML parse error on prefect-server/templates/agent/deployment.yaml: error converting YAML to JSON: yaml: line 61: did not find expected key`
`helm template helm/prefect-server …
> Fix Agent Helm chart template env block

- helm/prefect-server/README.md
- helm/prefect-server/values.yaml
Clarifying how the Kubernetes secret should be set on the Helm chart values when using an existing Postgres database rather than the one included with a sub-chart.
> Clarify how to set password for the Postgres database in the Server Helm chart documentation

- changes/pr320.yaml
- src/prefect_server/config.toml
- src/prefect_server/graphql/artifacts.py
Makes the payload size configurable for artifact creation.
Allows users to create larger artifacts than default 1 Mb. 
This PR:
Fixes #319
> feat: configurable artifact max payload size

- changes/pr322.yaml
- helm/prefect-server/templates/agent/deployment.yaml
- helm/prefect-server/values.yaml
This allows setting a custom job template directly on the `values.yaml` file.
In our use case, the only thing we needed to do was to set environment variables for all our jobs using `envFrom`. With this change (tested and working for us) it allows us to change the job template directly on the `values.yaml` file, making it much easier to manage.
This PR:
> [Feature] Allows custom job templates on helm chart

- changes/pr327.yaml
- helm/prefect-server/templates/agent/deployment.yaml
- helm/prefect-server/templates/apollo/deployment.yaml
- helm/prefect-server/templates/graphql/deployment.yaml
- helm/prefect-server/templates/hasura/deployment.yaml
- helm/prefect-server/templates/towel/deployment.yaml
- helm/prefect-server/templates/ui/deployment.yaml
- helm/prefect-server/values.yaml
Closes #318 
Adding `podAnnotations` field for each deployment to allow attaching arbitrary metadata to pods.
Useful for e.g. monitoring tools. See the issue #318 description for more info
This PR:
> Add podAnnotations to helm chart.

- .circleci/config.yml
- changes/pr328.yaml
- docker/infrastructure/docker-compose.yml
- helm/prefect-server/templates/hasura/deployment.yaml
- helm/prefect-server/values.yaml
- services/hasura/migrations/metadata.yaml
- src/prefect_server/cli/hasura.py
- tests/api/test_logs.py
Upgrades Hasura to v.2.0.9
Prefect Server is on a very old version of Hasura. Upgrading to v.2.0.9 allows it to keep up with current functionality.
This PR:
~~- [ ] adds new tests (if appropriate)~~
> upgrade to hasura2.0

- changes/issue331.yaml
- helm/prefect-server/values.yaml
The default values for the different env variables in the helm chart values.yaml file are set to an empty map, but the templates are setup so that you need to pass in a list. This causes a conflict when you try and set these values. This PR updates the default env values to an empty list.
See issue https://github.com/PrefectHQ/server/issues/331
If you attempt to pass in values for the env you get an error:
```
Error: failed parsing --set data: unable to parse key: interface conversion: interface {} is map[string]interface {}, not []interface {}
```
This PR:
> fix: Change default helm env values from map to list

- changes/pr316.yaml
- helm/prefect-server/templates/towel/deployment.yaml
Closes https://github.com/PrefectHQ/server/issues/315
Without the rest of the PG connection string (`{{ include "prefect-server.postgres-connstr" . }}`) the password seems useless.
Compare it for example to hasura that receives both the connection string and the password
https://github.com/PrefectHQ/server/blob/e8845108459c6889b1e359b260681a91533173f8/helm/prefect-server/templates/hasura/deployment.yaml#L50-L54
This PR:
> Don't pass pgpassword to towel.

- changes/pr350.yaml
- src/prefect_server/services/towel/lazarus.py
Reduces the maximum amount of flow runs Lazarus will query for at once.
With sufficient stress placed on the database, `Lazarus.reschedule_flow_runs` will time out and raise an exception, effectively breaking Lazarus. Reducing the limit in this PR reduces the chance the query will time out.
This PR:
> Reduce flow run reschedule limit on Lazarus

- .github/workflows/helm-release.yml
Using `git://` without authentication is [no longer supported](https://github.blog/2021-09-01-improving-git-protocol-security-github/) and causes the following failure resulting in invalid version tags in the published chart.
```
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
Closes https://github.com/PrefectHQ/server/issues/361 and #357
> Use https to retrieve latest tags for Helm chart pins

- helm/prefect-server/values.yaml
Bumping hasura image to 2.1.1 to match docker compose and include fix for M1 mac
Bumping hasura image to 2.1.1 to match docker compose and include fix for M1 mac
This probably should have been included in [PR 337](https://github.com/PrefectHQ/server/pull/337)
Fixes issues with M1 mac
This PR:
> Bumping hasura image to 2.1.1 - helm

- changes/380.yaml
- helm/prefect-server/templates/agent/deployment.yaml
helm: create agent's env vars only if input variables are not empty
Without this PR, helm with default values.yaml (e.g.  `agent: job : imagePullSecrets: []`) creates empty environment variable IMAGE_PULL_SECRETS in agent's pod that takes precedes over imagePullSecrets from serviceaccount or job template file.
This PR:
> helm: create agent's env vars only if input variables are not empty

- changes/379.yaml
- helm/prefect-server/templates/agent/deployment.yaml
- helm/prefect-server/values.yaml
This PR will allow helm users to specify a Kubernetes configmap to be mounted as jobTemplateFile to the agent's container/pod.
This PR:
> Helm: mount jobTemplateFile from Kubernetes configmap

- changes/pr371.md
- helm/prefect-server/templates/jobs/create_tenant.yaml
- helm/prefect-server/values.yaml
Add the ability to specify resources for the Create Tenant job specified in the Prefect Server helm chart.
Kubernetes clusters that have resource quotas require resources to be specified for every pod. This means the Create Tenant job cannot be run in such a cluster with the current helm chart.
This PR:
> Add resources for the Create Tenant job in Prefect Server Helm chart

- setup.py
Avoids breaking change for strict asyncio mode. Extends #382.
> Add upper pin to `pytest-asyncio`

- Changelog.md
- changes/379.yaml
- changes/380.yaml
- changes/pr370.yaml
WARNING: This release of the Helm chart includes a breaking change with the upgrade from PostgreSQL 9 to 11. This is required because bitnami no longer hosts the old version of Postgres. If updating from a prior Helm chart release, please take care to back up your database.
- Allow users to specify a Kubernetes config map to be mounted as `jobTemplateFile` in the agent's container - [#379](https://github.com/PrefectHQ/server/pull/379)
- Improve init container template for graphql - [#370](https://github.com/PrefectHQ/server/pull/370)
- Create agent's env vars only if input variables are not empty - [#380](https://github.com/PrefectHQ/server/pull/380)
- Update PostgreSQL from ~9 to ~11 — [#375](https://github.com/PrefectHQ/server/pull/375)
- Allow specification of resources for the tenant …
> Release 2022.09.07

- .circleci/config.yml
Install Prefect 1 from the 1.x branch, instead of master.
This PR:
> Backport: Install prefect from 1.x branch

- helm/prefect-server/templates/_helpers.tpl
Account for nesting of `postgresql.existingSecret` into `postgresql.auth.existingSecret`
nesting was increased in https://github.com/PrefectHQ/server/commit/fc97f3209c8e453f21f56164eb4ba830df272e03
This PR:
> Account for nesting of postgresql.existingSecret

- changes/pr407.yaml
- helm/prefect-server/README.md
- helm/prefect-server/values.yaml
The documentation refers to different secret than is actually used in the Helm chart. [Although, I actually think the secret is renamed at some point 🤷 ].
If the wrong secret is configured, the pods will never come online:
```
CreateContainerConfigError: couldn't find key postgres-password in Secret prefect/prefect-postgresql 
```
This PR:
> docs: fix postgresql-password -> postgres-password
